# Generated by Django 2.2.4 on 2019-08-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TouchupPaintTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchuppaints',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
