# Generated by Django 2.2.4 on 2019-08-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TouchupPaintTracker', '0002_touchuppaints_in_use'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TouchUpPaints',
            new_name='TouchUpPaint',
        ),
    ]
